[build]
  base = "web/"
  command = "yarn build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    cache-control = 'public'
    max-age = '31536000'
    stale-while-revalidate = '86400'

[[headers]]
  for = "/fonts/*"
  [headers.values]
    cache-control = 'public'
    max-age = '31536000'
    stale-while-revalidate = '86400'
    
[[headers]]
  for = "/icons/*"
  [headers.values]
    cache-control = 'public'
    max-age = '31536000'
    stale-while-revalidate = '86400'

[[headers]]
  for = "/images/*"
  [headers.values]
    cache-control = 'public'
    max-age = '31536000'
    stale-while-revalidate = '86400'
    
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["metronome-sh"]